pandoc -s 'markdown/F. J. Bergmann - Falling Barometer.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Falling Barometer.tex'
pandoc -s 'markdown/Daniel G. Fitch - Civilization_ A Work in Progress.markdown' -f markdown -t latex -o 'tex/Daniel G. Fitch - Civilization_ A Work in Progress.tex'
pandoc -s 'markdown/Julie Fitzpatrick - Bad Day.markdown' -f markdown -t latex -o 'tex/Julie Fitzpatrick - Bad Day.tex'
pandoc -s 'markdown/F. J. Bergmann - Contrarian.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Contrarian.tex'
pandoc -s 'markdown/F. J. Bergmann - Mirror.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Mirror.tex'
pandoc -s 'markdown/F. J. Bergmann - Information Technology.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Information Technology.tex'
pandoc -s 'markdown/F. J. Bergmann - Pilgrimage.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Pilgrimage.tex'
pandoc -s 'markdown/F. J. Bergmann - Appropriate Tools.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Appropriate Tools.tex'
pandoc -s 'markdown/F. J. Bergmann - The Green Sun is Not a Sun.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - The Green Sun is Not a Sun.tex'
pandoc -s 'markdown/Bhim Nimgade - Flying From This World.markdown' -f markdown -t latex -o 'tex/Bhim Nimgade - Flying From This World.tex'
pandoc -s 'markdown/F. J. Bergmann - Inclusions.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Inclusions.tex'
pandoc -s 'markdown/F. J. Bergmann - Synecdoche.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Synecdoche.tex'
pandoc -s 'markdown/F. J. Bergmann - The Way Home.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - The Way Home.tex'
pandoc -s 'markdown/F. J. Bergmann - Un-Becoming.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Un-Becoming.tex'
pandoc -s 'markdown/Julie Fitzpatrick - Free Beer.markdown' -f markdown -t latex -o 'tex/Julie Fitzpatrick - Free Beer.tex'
pandoc -s 'markdown/Andy Dibble - Holiday Gifts.markdown' -f markdown -t latex -o 'tex/Andy Dibble - Holiday Gifts.tex'
pandoc -s 'markdown/Daniel G. Fitch - Divisor.markdown' -f markdown -t latex -o 'tex/Daniel G. Fitch - Divisor.tex'
pandoc -s 'markdown/F. J. Bergmann - Cousin Art.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Cousin Art.tex'
pandoc -s 'markdown/Daniel G. Fitch - Enticement.markdown' -f markdown -t latex -o 'tex/Daniel G. Fitch - Enticement.tex'
pandoc -s 'markdown/Andy Dibble - The Search for Sky.markdown' -f markdown -t latex -o 'tex/Andy Dibble - The Search for Sky.tex'
pandoc -s 'markdown/F. J. Bergmann - Evil Clowns.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Evil Clowns.tex'
pandoc -s 'markdown/F. J. Bergmann - Corporate Art Collection.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Corporate Art Collection.tex'
pandoc -s 'markdown/Julie Fitzpatrick - Third Strike_.markdown' -f markdown -t latex -o 'tex/Julie Fitzpatrick - Third Strike_.tex'
pandoc -s 'markdown/F. J. Bergmann - Guns, Butter_.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Guns, Butter_.tex'
pandoc -s 'markdown/F. J. Bergmann - Containers.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Containers.tex'
pandoc -s 'markdown/Julie Fitzpatrick - An Invitation to Eat Sunshine.markdown' -f markdown -t latex -o 'tex/Julie Fitzpatrick - An Invitation to Eat Sunshine.tex'
pandoc -s 'markdown/F. J. Bergmann - Maize.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Maize.tex'
pandoc -s 'markdown/Andy Dibble - One Last Belly Rub.markdown' -f markdown -t latex -o 'tex/Andy Dibble - One Last Belly Rub.tex'
pandoc -s 'markdown/F. J. Bergmann - Love You till the End.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Love You till the End.tex'
pandoc -s 'markdown/Daniel G. Fitch - On Stellar Winds, Writhing Ecstatic.markdown' -f markdown -t latex -o 'tex/Daniel G. Fitch - On Stellar Winds, Writhing Ecstatic.tex'
pandoc -s 'markdown/Jesse Giallombardo - Access.markdown' -f markdown -t latex -o 'tex/Jesse Giallombardo - Access.tex'
pandoc -s 'markdown/F. J. Bergmann - Self-Preservation.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Self-Preservation.tex'
pandoc -s 'markdown/F. J. Bergmann - Creatures of Habit.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Creatures of Habit.tex'
pandoc -s 'markdown/Daniel G. Fitch - Murmuring Hinge.markdown' -f markdown -t latex -o 'tex/Daniel G. Fitch - Murmuring Hinge.tex'
pandoc -s 'markdown/F. J. Bergmann - Blessing the Wind.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Blessing the Wind.tex'
pandoc -s 'markdown/F. J. Bergmann - Duration.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Duration.tex'
pandoc -s 'markdown/F. J. Bergmann - The Doorman.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - The Doorman.tex'
pandoc -s 'markdown/F. J. Bergmann - Sky Blue.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Sky Blue.tex'
pandoc -s 'markdown/F. J. Bergmann - Propagation.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Propagation.tex'
pandoc -s 'markdown/F. J. Bergmann - Transmutation.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Transmutation.tex'
pandoc -s 'markdown/F. J. Bergmann - Marshmallows_.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Marshmallows_.tex'
pandoc -s 'markdown/Daniel G. Fitch - Catchcry.markdown' -f markdown -t latex -o 'tex/Daniel G. Fitch - Catchcry.tex'
pandoc -s 'markdown/Andy Dibble - The Last Laugh.markdown' -f markdown -t latex -o 'tex/Andy Dibble - The Last Laugh.tex'
pandoc -s 'markdown/F. J. Bergmann - The White Foal.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - The White Foal.tex'
pandoc -s 'markdown/Julie Fitzpatrick - Reflection for Hard Times.markdown' -f markdown -t latex -o 'tex/Julie Fitzpatrick - Reflection for Hard Times.tex'
pandoc -s 'markdown/F. J. Bergmann - Pontifex_.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Pontifex_.tex'
pandoc -s 'markdown/F. J. Bergmann - The Interpretation of Dreams.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - The Interpretation of Dreams.tex'
pandoc -s 'markdown/Bhim Nimgade - Luc and Beto at the End of the World.markdown' -f markdown -t latex -o 'tex/Bhim Nimgade - Luc and Beto at the End of the World.tex'
pandoc -s 'markdown/F. J. Bergmann - Companion to the Guide to the Norton Reader.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Companion to the Guide to the Norton Reader.tex'
pandoc -s 'markdown/F. J. Bergmann - Thrall.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Thrall.tex'
pandoc -s 'markdown/F. J. Bergmann - Cadastral.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Cadastral.tex'
pandoc -s 'markdown/F. J. Bergmann - The Origin of Fruitcakes.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - The Origin of Fruitcakes.tex'
pandoc -s 'markdown/F. J. Bergmann - EEE-k.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - EEE-k.tex'
pandoc -s 'markdown/Andy Dibble - Three Poems.markdown' -f markdown -t latex -o 'tex/Andy Dibble - Three Poems.tex'
pandoc -s 'markdown/F. J. Bergmann - Glossolithia.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Glossolithia.tex'
pandoc -s 'markdown/F. J. Bergmann - Wall.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Wall.tex'
pandoc -s 'markdown/Bhim Nimgade - Harvest for the Dying.markdown' -f markdown -t latex -o 'tex/Bhim Nimgade - Harvest for the Dying.tex'
pandoc -s 'markdown/Bhim Nimgade - Boromilla Calls Us Back.markdown' -f markdown -t latex -o 'tex/Bhim Nimgade - Boromilla Calls Us Back.tex'
pandoc -s 'markdown/F. J. Bergmann - Multi-tasking.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Multi-tasking.tex'
pandoc -s 'markdown/F. J. Bergmann - Supermouse.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Supermouse.tex'
pandoc -s 'markdown/F. J. Bergmann - Foreseeable Future.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Foreseeable Future.tex'
pandoc -s 'markdown/Bhim Nimgade - Faces Floating Up.markdown' -f markdown -t latex -o 'tex/Bhim Nimgade - Faces Floating Up.tex'
pandoc -s 'markdown/Bhim Nimgade - Tiny Soldiers.markdown' -f markdown -t latex -o 'tex/Bhim Nimgade - Tiny Soldiers.tex'
pandoc -s 'markdown/F. J. Bergmann - Cetaceae.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Cetaceae.tex'
pandoc -s 'markdown/F. J. Bergmann - Boundaries.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Boundaries.tex'
pandoc -s 'markdown/F. J. Bergmann - Dalliance.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Dalliance.tex'
pandoc -s 'markdown/Daniel G. Fitch - Superarbitrage.markdown' -f markdown -t latex -o 'tex/Daniel G. Fitch - Superarbitrage.tex'
pandoc -s 'markdown/Bhim Nimgade - The Glorious Perorations Picnic.markdown' -f markdown -t latex -o 'tex/Bhim Nimgade - The Glorious Perorations Picnic.tex'
pandoc -s 'markdown/F. J. Bergmann - Half-Mourning.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Half-Mourning.tex'
pandoc -s 'markdown/F. J. Bergmann - Nostalgia.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Nostalgia.tex'
pandoc -s 'markdown/F. J. Bergmann - Astroculture.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Astroculture.tex'
pandoc -s 'markdown/Bhim Nimgade - The Reading Room.markdown' -f markdown -t latex -o 'tex/Bhim Nimgade - The Reading Room.tex'
pandoc -s 'markdown/Julie Fitzpatrick - Man vs. Faery.markdown' -f markdown -t latex -o 'tex/Julie Fitzpatrick - Man vs. Faery.tex'
pandoc -s 'markdown/F. J. Bergmann - OPERATION TO DISSEVER SOUL FROM EX-GIRLFRIEND’S SOUL SUCCESSFUL.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - OPERATION TO DISSEVER SOUL FROM EX-GIRLFRIEND’S SOUL SUCCESSFUL.tex'
pandoc -s 'markdown/Julie Fitzpatrick - Reflection for Frustrating Times.markdown' -f markdown -t latex -o 'tex/Julie Fitzpatrick - Reflection for Frustrating Times.tex'
pandoc -s 'markdown/F. J. Bergmann - Blight.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Blight.tex'
pandoc -s 'markdown/F. J. Bergmann - Ascent_.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Ascent_.tex'
pandoc -s 'markdown/Julie Fitzpatrick - Fetch.markdown' -f markdown -t latex -o 'tex/Julie Fitzpatrick - Fetch.tex'
pandoc -s 'markdown/F. J. Bergmann - Enter Here.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Enter Here.tex'
pandoc -s 'markdown/Daniel G. Fitch - Spear Theory.markdown' -f markdown -t latex -o 'tex/Daniel G. Fitch - Spear Theory.tex'
pandoc -s 'markdown/F. J. Bergmann - Calligraphy.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Calligraphy.tex'
pandoc -s 'markdown/Jesse Giallombardo - The Tree.markdown' -f markdown -t latex -o 'tex/Jesse Giallombardo - The Tree.tex'
pandoc -s 'markdown/F. J. Bergmann - Phantom Limb.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Phantom Limb.tex'
pandoc -s 'markdown/F. J. Bergmann - . . . But Paranormal Revenge Is Crappy.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - . . . But Paranormal Revenge Is Crappy.tex'
pandoc -s 'markdown/Daniel G. Fitch - After the Image.markdown' -f markdown -t latex -o 'tex/Daniel G. Fitch - After the Image.tex'
pandoc -s 'markdown/F. J. Bergmann - Permanent Resident.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Permanent Resident.tex'
pandoc -s 'markdown/Julie Fitzpatrick - The Woman With No Niche.markdown' -f markdown -t latex -o 'tex/Julie Fitzpatrick - The Woman With No Niche.tex'
pandoc -s 'markdown/F. J. Bergmann - Terminus_.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Terminus_.tex'
pandoc -s 'markdown/F. J. Bergmann - Solitude.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Solitude.tex'
pandoc -s 'markdown/Julie Fitzpatrick - Beelzabottle.markdown' -f markdown -t latex -o 'tex/Julie Fitzpatrick - Beelzabottle.tex'
pandoc -s 'markdown/F. J. Bergmann - Stuffed Head.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Stuffed Head.tex'
pandoc -s 'markdown/F. J. Bergmann - Snowfall.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - Snowfall.tex'
pandoc -s 'markdown/F. J. Bergmann - The Drawing Room.markdown' -f markdown -t latex -o 'tex/F. J. Bergmann - The Drawing Room.tex'
